server:
  port: ${SERVER_PORT:8082}
  error:
    include-message: always
    include-exception: true

spring:
  application:
    name: ${APP_NAME:auth}
  tomcat:
    threads:
      max: 300
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${AUTH_SERVER_URL:http://keycloak:8880}/realms/${AUTH_SERVER_REALM:image-processing}
          jwk-set-uri:  ${AUTH_SERVER_URL:http://keycloak:8880}/realms/${AUTH_SERVER_REALM:image-processing}/protocol/openid-connect/certs

keycloak:
  auth-server-url: ${AUTH_SERVER_URL:http://keycloak:8880}
  realm: ${AUTH_SERVER_REALM:image-processing}
  client-id: ${AUTH_SERVER_CLIENT_ID:image-processing-admin}
  client-secret: ${AUTH_SERVER_CLIENT_SECRET:kqDoa2+jTLpdO5Ab4yqAAqrcDN7AvMXe}

springdoc:
  api-docs:
    path: /api-docs/gateway/v3/api-docs
  swagger-ui:
    path: /api-docs/gateway/swagger-ui
    display-request-duration: true
    disable-swagger-default-url: true
    urls:
      - name: gateway
        url: ${API_URL:http://localhost:8082}/api-docs/gateway/v3/api-docs
    urls-primary-name: gateway
    url:  ${PUBLIC_URL:http://localhost:8082}/
  show-actuator: false
  enable-groovy: false

feign:
  auth:
    url: ${AUTH_URL:http://localhost:8081}
  store:
    url: ${STORE_URL:http://localhost:8080}