services:
  postgresql:
    image: postgres:${POSTGRESQL_VERSION}
    container_name: ${PROJECT_NAME_PREFIX}-postgresql
    hostname: postgresql
    environment:
      PGDATA: /var/lib/postgresql/pgdata4
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    volumes:
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
      - postgres_data:/var/lib/postgresql/pgdata4
    healthcheck:
      test: [ "CMD-SHELL", "exec pg_isready -U ${POSTGRES_USERNAME} -d keycloak" ]
      interval: 5s
      timeout: 60s
      retries: 5
      start_period: 80s
    networks:
      - msa-network
    ports:
      - 5432:5432
  smtp4dev:
    image: rnwood/smtp4dev:v3
    container_name: ${PROJECT_NAME_PREFIX}-smtp4dev
    hostname: smtp4dev
    ports:
      - "3000:80"         # Web UI port
      - "2525:25"         # SMTP port (for receiving emails)
      - "465:465"         # SMTPS port (SSL/TLS)
      - "587:587"         # Submission port (STARTTLS)
    networks:
      - msa-network
    restart: unless-stopped
    environment:
      - Smtp4Dev__DisableMessageSanitization=true  # Allows HTML emails
      #- Smtp4Dev__ServerOptions__RequireAuthentication=true  # Enable auth
      #- Smtp4Dev__ServerOptions__AllowRemoteConnections=true  # Allow remote access
  keycloak:
    image: quay.io/keycloak/keycloak:${KEYCLOAK_VERSION}
    container_name: ${PROJECT_NAME_PREFIX}-keycloak
    hostname: keycloak
    environment:
      KC_DB: postgres
      DB_VENDOR: POSTGRES
      DB_ADDR: postgresql
      DB_DATABASE: ${DB_DATABASE}
      DB_SCHEMA: public
      KC_DB_URL: jdbc:postgresql://postgresql/${DB_DATABASE}
      KC_DB_USERNAME: ${KC_DB_USERNAME}
      KC_DB_PASSWORD: ${KC_DB_PASSWORD}
      KC_HOSTNAME: keycloak
      KC_HEALTH_ENABLED: true
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN_USERNAME}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      KC_HTTP_PORT: 8880
    ports:
      - '8880:8880'
    command: start-dev --import-realm
    healthcheck:
      test: [ "CMD-SHELL", 'exec 3<>/dev/tcp/localhost/8880; echo -e "GET /health/ready HTTP/1.1\nhost: localhost:8880\n" >&3; timeout --preserve-status 1 cat <&3 | grep -m 1 status | grep -m 1 UP; ERROR=$?; exec 3<&-; exec 3>&-; exit $ERROR' ]
      start_period: 10s
      interval: 30s
      retries: 3
      timeout: 5s
    volumes:
      - ./keycloak:/opt/keycloak/data/import:ro
    depends_on:
      postgresql:
        condition: service_healthy
    networks:
      - msa-network
  minio:
    image: minio/minio
    container_name: ${PROJECT_NAME_PREFIX}-minio
    hostname: minio
    command: server /data --console-address ":9090"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    volumes:
#      - ./minio/minio-data:/data
      - ./minio/preload-files:/preload
    entrypoint: >
      /bin/sh -c '
        set -e
        isAlive() { curl -sf http://127.0.0.1:9000/minio/health/live; }
        
        bucketExists() {
            mc ls local/$1 >/dev/null 2>&1
        }
        
        # Запускаем MinIO в фоновом режиме
        minio server /data --console-address ":9001" &
      
        # Ждём пока MinIO запустится
        while ! mc alias set local http://localhost:9000 admin admin123 2>/dev/null; do
          sleep 1
        done
      
        # Создаём бакеты и копируем файлы
        if ! bucketExists ${S3_STORE_BUCKET}; then
            mc mb local/${S3_STORE_BUCKET}
        fi
        if ! bucketExists ${S3_NOTIFICATION_BUCKET}; then
            mc mb local/${S3_NOTIFICATION_BUCKET}
        fi
        mc cp --recursive /preload/ local/notifications/
      
        # Возвращаем MinIO на передний план
        while isAlive; do sleep 0.1; done
        exec minio $0 "$@"
      '
    ports:
      - "9000:9000"
      - "9001:9001"
    networks:
      - msa-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
  rabbitmq:
    image: rabbitmq:3.12-management
    container_name: ${PROJECT_NAME_PREFIX}-rabbitmq
    hostname: rabbitmq
    ports:
      - "5672:5672"   # AMQP порт
      - "15672:15672" # Web UI порт
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=password
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - msa-network
  fluent-bit:
    image: fluent/fluent-bit:4.0.5
    container_name: ${PROJECT_NAME_PREFIX}-fluent-bit
    hostname: fluent-bit
    ports:
      - 24224:24224
      - 24224:24224/udp
    volumes:
      - ./fluent-bit/fluent-bit.conf:/fluent-bit/etc/fluent-bit.conf
    networks:
      - msa-network
  victorialogs:
    image: victoriametrics/victoria-logs:v1.26.0
    hostname: victorialogs
    container_name: ${PROJECT_NAME_PREFIX}-victorialogs
    restart: unless-stopped
    ports:
      - "9428:9428"
    volumes:
      - victorialogs_data:/storage
    command:
      - --storageDataPath=/storage
      - --httpListenAddr=:9428
    networks:
      - msa-network
  prometheus:
    image: prom/prometheus:v3.5.0
    container_name: ${PROJECT_NAME_PREFIX}-prometheus
    hostname: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus/targets.json:/etc/prometheus/targets.json
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    networks:
      - msa-network
  grafana:
    image: grafana/grafana:12.1.0
    hostname: grafana
    container_name: ${PROJECT_NAME_PREFIX}-grafana
    ports:
      - "5000:3000"
    depends_on:
      - prometheus
    volumes:
      - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
      - ./grafana/provisioning/dashboards/dashboards.yaml:/etc/grafana/provisioning/dashboards/main.yaml
      - ./grafana/dashboards:/var/lib/grafana/dashboards
    networks:
      - msa-network
  s3-store:
    image: ${PROJECT_NAME_PREFIX}/aws-storage:latest
    container_name: ${PROJECT_NAME_PREFIX}-s3-store
    hostname: s3-store
    depends_on:
      - keycloak
      - rabbitmq
      - fluent-bit
    environment:
      - AUTH_SERVER_URL=${KEYCLOAK_ENDPOINT}
      - S3_ENDPOINT=${S3_ENDPOINT}
      - S3_ACCESS_KEY=${MINIO_ROOT_USER}
      - S3_SECRET_KEY=${MINIO_ROOT_PASSWORD}
      - RABBIT_HOST=${RABBIT_HOST}
      - RABBIT_PORT=${RABBIT_PORT}
      - RABBIT_USERNAME=${RABBIT_USERNAME}
      - RABBIT_PASSWORD=${RABBIT_PASSWORD}
    networks:
      - msa-network
    ports:
      - 8080:8080
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: store.logs
  auth:
    image: ${PROJECT_NAME_PREFIX}/auth:latest
    container_name: ${PROJECT_NAME_PREFIX}-auth
    hostname: auth
    depends_on:
      - keycloak
      - fluent-bit
    environment:
      - AUTH_SERVER_URL=${KEYCLOAK_ENDPOINT}
    networks:
      - msa-network
    ports:
      - 8081:8081
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: auth.logs
  gateway:
    image: ${PROJECT_NAME_PREFIX}/gateway
    container_name: ${PROJECT_NAME_PREFIX}-gateway
    hostname: gateway
    depends_on:
      - keycloak
      - fluent-bit
    environment:
      - AUTH_SERVER_URL=${KEYCLOAK_ENDPOINT}
      - STORE_URL=${STORE_URL}
      - AUTH_URL=${AUTH_URL}
      - NOTIFICATION_URL=${NOTIFICATION_URL}
    networks:
      - msa-network
    ports:
      - 8082:8082
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: gateway.logs
  notification:
    image: ${PROJECT_NAME_PREFIX}/notification
    container_name: ${PROJECT_NAME_PREFIX}-notification
    hostname: notification
    depends_on:
      - keycloak
      - fluent-bit
    environment:
      - AUTH_SERVER_URL=${KEYCLOAK_ENDPOINT}
      - S3_ENDPOINT=${S3_ENDPOINT}
      - S3_ACCESS_KEY=${MINIO_ROOT_USER}
      - S3_SECRET_KEY=${MINIO_ROOT_PASSWORD}
      - S3_STORE_BUCKET=${S3_NOTIFICATION_BUCKET}
      - MAIL_HOST=smtp4dev
      - MAIL_PORT=25
      - RABBIT_HOST=${RABBIT_HOST}
      - RABBIT_PORT=${RABBIT_PORT}
      - RABBIT_USERNAME=${RABBIT_USERNAME}
      - RABBIT_PASSWORD=${RABBIT_PASSWORD}
      - AUTH_URL=${AUTH_URL}
    networks:
      - msa-network
    ports:
      - 8083:8083
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: notification.logs
networks:
  msa-network:
    driver: bridge
    name: msa-network
volumes:
  postgres_data:
    driver: local
  rabbitmq_data:
  victorialogs_data: