server:
  port: ${SERVER_PORT:8081}

spring:
  application:
    name: ${APP_NAME:auth}
  tomcat:
    threads:
      max: 300
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${AUTH_SERVER_URL:http://keycloak:8880}/realms/${AUTH_SERVER_REALM:image-processing}
          jwk-set-uri:  ${AUTH_SERVER_URL:http://keycloak:8880}/realms/${AUTH_SERVER_REALM:image-processing}/protocol/openid-connect/certs

keycloak:
  auth-server-url: ${AUTH_SERVER_URL:http://keycloak:8880}
  realm: ${AUTH_SERVER_REALM:image-processing}
  client-id: ${AUTH_SERVER_CLIENT_ID:image-processing-admin}
  client-secret: ${AUTH_SERVER_CLIENT_SECRET:kqDoa2+jTLpdO5Ab4yqAAqrcDN7AvMXe}

springdoc:
  api-docs:
    path: /api-docs/auth/v3/api-docs
  swagger-ui:
    path: /api-docs/auth/swagger-ui
    display-request-duration: true
    disable-swagger-default-url: true
    urls:
      - name: auth
        url: ${API_URL:http://localhost:8081}/api-docs/auth/v3/api-docs
    urls-primary-name: auth
    url:  ${PUBLIC_URL:http://localhost:8081}/
  show-actuator: false
  enable-groovy: false