server:
  port: ${SERVER_PORT:8081}
  error:
    include-message: always
    include-exception: true

spring:
  application:
    name: ${APP_NAME:auth}
  tomcat:
    threads:
      max: 300
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${AUTH_SERVER_URL:http://keycloak:8880}/realms/${AUTH_SERVER_REALM:msa-application}
          jwk-set-uri:  ${AUTH_SERVER_URL:http://keycloak:8880}/realms/${AUTH_SERVER_REALM:msa-application}/protocol/openid-connect/certs
  cache:
    type: caffeine
    cache-names: userInfo # Pre-configured cache names
    caffeine:
      spec: maximumSize=100,expireAfterWrite=60m  # Global Caffeine specification

keycloak:
  auth-server-url: ${AUTH_SERVER_URL:http://keycloak:8880}
  realm: ${AUTH_SERVER_REALM:msa-application}
  client-id: ${AUTH_SERVER_CLIENT_ID:msa-application-admin}
  client-secret: ${AUTH_SERVER_CLIENT_SECRET:kqDoa2+jTLpdO5Ab4yqAAqrcDN7AvMXe}

springdoc:
  api-docs:
    path: /api-docs/auth/v3/api-docs
  swagger-ui:
    path: /api-docs/auth/swagger-ui
    display-request-duration: true
    disable-swagger-default-url: true
    urls:
      - name: auth
        url: ${API_URL:http://localhost:8081}/api-docs/auth/v3/api-docs
    urls-primary-name: auth
    url:  ${PUBLIC_URL:http://localhost:8081}/
  show-actuator: false
  enable-groovy: false

management:
  endpoints:
    web:
      exposure:
        include: health,info,loggers,prometheus
  endpoint:
    health:
      show-details: ALWAYS
  metrics:
    tags:
      application: ${spring.application.name}
  prometheus:
    metrics:
      export:
        enabled: true