openapi: 3.0.0
info:
  title: Image Storage Service API
  description: Microservice for storing images (AWS S3 / MinIO)
  version: 1.0.0
servers:
  - url: http://localhost:8080/api/v1
    description: Local server
  - url: https://api.your-storage-service.com/api/v1
    description: Production server

tags:
  - name: Storage
    description: Image storage management

paths:
  /api/v1/storage/upload:
    post:
      tags: [Storage]
      summary: Upload an image
      operationId: upload
      description: Uploads a file to S3/MinIO and returns its unique ID.
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: string
                  format: binary
                  description: Image file (JPEG, PNG, etc.)
      responses:
        '200':
          description: File uploaded successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  fileId:
                    type: string
                    example: "a1b2c3d4-e5f6-7890"
                  url:
                    type: string
                    example: "http://minio-bucket.s3.amazonaws.com/a1b2c3d4.jpg"
        '400':
          description: Invalid file format
        '500':
          description: Server error during upload

  /api/v1/storage/{fileId}:
    get:
      tags: [Storage]
      summary: Download an image
      operationId: download
      description: Returns the image file as a binary stream (application/octet-stream).
      parameters:
        - in: path
          name: fileId
          required: true
          schema:
            type: string
          description: Unique file ID
      responses:
        '200':
          description: File found
          content:
            application/octet-stream:
              schema:
                type: string
                format: binary
          headers:
            Content-Disposition:
              schema:
                type: string
              description: Filename (e.g., "attachment; filename=image.jpg")
        '404':
          description: File not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

    delete:
      tags: [Storage]
      summary: Delete an image
      operationId: delete
      description: Deletes a file from storage.
      parameters:
        - in: path
          name: fileId
          required: true
          schema:
            type: string
      responses:
        '204':
          description: File deleted successfully
        '404':
          description: File not found
        '500':
          description: Server error

  /api/v1/storage/{fileId}/metadata:
    get:
      tags: [Storage]
      summary: Get file metadata
      operationId: getMetadata
      description: Returns metadata (size, format, creation date) of the image.
      parameters:
        - in: path
          name: fileId
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Metadata retrieved
          content:
            application/json:
              schema:
                type: object
                properties:
                  fileId:
                    type: string
                  size:
                    type: integer
                    example: 1024
                  format:
                    type: string
                    example: "JPEG"
                  lastModified:
                    type: string
                    format: date-time
        '404':
          description: File not found

components:
  schemas:
    ErrorResponse:
      type: object
      properties:
        error:
          type: string
          example: "File not found"
        status:
          type: integer
          example: 404